Add vmstat metrics to meminfo_numa
kwisniewski98/node_exporter pull request #1
Opened 2020-09-16 10:07 UTC by kwisniewski98

Signed-off-by: Wisniewski, Krzysztof2 <Krzysztof2.Wisniewski@intel.com>

2020-09-25 06:43 UTC, katarzyna-z reviewed
It will be good to add unit tests for this code? Is it possible?

2020-09-25 06:43 UTC, katarzyna-z commented on collector/meminfo_numa_linux.go
> +		vmStat, err := parseVMStatNuma(vmstatFile, nodeNumber[1])
Are you sure that at this point `nodeNumber` contains at least 2 elements?

2020-12-08 11:47 UTC, Creatone commented on collector/meminfo_numa_linux.go
> +		if nodeNumber == nil || len(nodeNumber) != 2 {
Maybe you can put that number into constant? Something like `expectedNodeNumberLength`.

2020-12-08 11:47 UTC, Creatone commented on collector/meminfo_numa_linux.go
> +		vmstat = append(vmstat, meminfoMetric{"vmstat_" + parts[0], prometheus.UntypedValue, nodeNumber, fv})
Why you use `prometheus.UntypedValue`?

```

2020-12-08 11:48 UTC, Creatone requested changes
Check this out

2021-02-18 13:34 UTC, closed without merging